name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/electron
            ~/Library/Caches/electron-builder
          key: mac-electron-${{ hashFiles('**/package-lock.json') }}
          restore-keys: mac-electron-
      - run: npm ci
      - name: Build & Publish (macOS)
        run: npm run build && npx electron-builder --mac --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\electron\Cache
            ~\AppData\Local\electron-builder\Cache
          key: win-electron-${{ hashFiles('**/package-lock.json') }}
          restore-keys: win-electron-
      - run: npm ci
      - name: Build & Publish (Windows)
        run: npm run build && npx electron-builder --win --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
